config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: "registrations"}
  root 'home#index'

  resources :comments do   
     resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
  end

  resources :articles do 
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do 
      resources :comments  
    end
  end

  resources :links do 
    resource :vote do
      put 'upvote'
      put 'downvote'
    end
    resources :comments do
      resources :comments  
    end
  end

  resources :videos do
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do
      resources :comments  
    end
  end

  resources :photos do
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do  
      resources :comments  
    end
  end

  

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, as: :commentable, :dependent => :destroy
	belongs_to :user
	has_many :votes, :as => :votable, :dependent => :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
  	@articles= Article.all
  	#render json: @article 
  end

  def new 
  	@article= current_user.articles.build
  end

  def edit
  end

  def create
  	@article = current_user.articles.build(article_params)

  	respond_to do |format|
  		if @article.save
  			format.html {redirect_to @article,notice: 'Article was successfuly created'}
  			format.json {render :show, status: :created , location: @artilce }
  		else
  			format.html {render :new}
  			format.json {render json: @article.errors, status: :unprocessable_entity}
  		end
  	end
  end

  def show
    @commentable=@article
    @comments = @commentable.comments
    @comment = Comment.new

     @votable=@article
    # @likes = @votable.votes.where(:emotion => 1).count
    # @dislikes = @votable.votes.where(:emotion => 2).count
  end

  def destroy
  	@article.destroy
  	respond_to do |format|
  		format.html {redirect_to articles_url, notice: 'Article was successfuly destroyed'}
  		format.json { head :no_content}
  	end
  end

  def update
  	respond_to do |format|
  		if @article.update(article_params)
  			format.html {redirect_to @article, notice: 'Article was successfuly updated'}
  			format.json {render :show, status: :updated , location: @article}
  		else
  			format.html {render :edit}
  			format.json {render json: @article.errors, status: :unprocessable_entity}
  		end
  	end
  end

  private

    def set_article
    	@article = Article.find(params[:id])
    end

    def article_params
    	params.require(:article).permit(:title, :text)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def markdown(text)
		options = {hard_wrap: true, filter_html: true, autolink: true, no_intraemphasis: true, fenced_code: true, gh_blockcode: true}
		markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, **options)
		markdown.render(text).html_safe
	end
end

app/views/articles/_form.html.erb
<%= form_for @article  do |f| %>
	<%= render 'shared/errors', object: @article %>
	<div class="form-group">
		<%= f.label :title%><br>
		<%= f.text_field :title, class: 'form-control'%>
	</div>

	<div class="form-group">
		<%= f.label :text, "Write your content here"%><br>
		<%= f.text_area :text, size:"100x10", class: 'form-control' %>
	</div>
	
	<div class="form-group">
		<%= f.submit 'Create Article', class: "btn btn-lg btn-primary" %>
	</div>
<% end %>

app/views/articles/edit.html.erb
<div class="post-block">
	<div class="page-header"><h1>Editing article</h1></div>
	<%= render 'form' %>

	<%= link_to 'Show', @article %> .
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<% if user_signed_in? %>
	<%= link_to 'New Article', new_article_path, class: 'btn btn-default' %>
<% end %>

<% @articles.each do |article|%>
  <div class="post-block">
	<div class="round-image-50"><%= image_tag article.user.avatar.url(:thumb) %></div>
	<h4>
        <%= link_to article.title, article_path(article)  %><br>
      <small class="author">Submitted <%= time_ago_in_words(article.created_at) %> by <%= article.user.name %></small>
    </h4>
	<p><%= truncate(article.text, :length => 300) %></p>
	
	<div class="btn-group">
		<%= link_to 'Show', article, class: 'btn btn-default btn-sm' %>

		<% if user_signed_in? and current_user.id == article.user_id %>
			<%= link_to 'Edit', edit_article_path(article) ,class: 'btn btn-default btn-sm' %>
			<%= link_to 'Delete', article, method: :delete, data: {confirm: 'Are you sure'} ,class: 'btn btn-default btn-sm' %>
		<% end %>
	</div>
  </div>
<%end%>

app/views/articles/new.html.erb
<div class="post-block">
	<div class="page-header"><h1>New Article</h1></div>
	<%= render 'form'%>
	<%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="post-block">
	<div class="page-header">
		<h1><%= @article.title %>
		<br><small>Submitted By <%= @article.user.name %></small></h1>
	</div>
	<p>
		<%= markdown(@article.text) %>
	</p>

	<% if current_user==@article.user %>
	 	<div class="btn-group">
			<%= link_to 'Edit',edit_article_path(@article), class: "btn btn-default" %>
	      <%= link_to 'Destroy', @article, method: :delete,data: {confirm: 'Are you sure?'},class: "btn btn-default"%>
	    </div>
	<% end %>
	
	<%= render "votes/show" %>
	<%= render  "comments/new" %>
	<%= render "comments/index" %> 
	
</div>