config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: "registrations"}
  root 'home#index'

  resources :comments do   
     resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
  end

  resources :articles do 
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do 
      resources :comments  
    end
  end

  resources :links do 
    resource :vote do
      put 'upvote'
      put 'downvote'
    end
    resources :comments do
      resources :comments  
    end
  end

  resources :videos do
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do
      resources :comments  
    end
  end

  resources :photos do
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do  
      resources :comments  
    end
  end

  

end

app/models/video.rb
class Video < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :as => :commentable, :dependent => :destroy
	has_many :votes, :as => :votable, :dependent => :destroy
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @commentable=@video
    @comments = @commentable.comments
    @comment = Comment.new

    @votable=@video
    # @likes = @votable.votes.where(:emotion => 1).count
    # @dislikes = @votable.votes.where(:emotion => 2).count
  end

  # GET /videos/new
  def new
    @video = current_user.videos.build
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = current_user.videos.build(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:url, :title, :description,:user_id,:video_id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper

	def embed(youtube_url)
		youtube_id = youtube_url.split("=").last
		content_tag(:iframe, nil,autohide: 0, :allowfullscreen => "allowfullscreen", src: "//www.youtube.com/embed/#{youtube_id}")
	end
	
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <%= render 'shared/errors', object: @video %>

  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description , class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.submit "Submit video", class: "btn btn-lg btn-primary"%>
  </div>

<% end %>

app/views/videos/edit.html.erb
<div class="post-block">
	<div class="page-header"><h1>Editing Video</h1></div>

	<%= render 'form' %>

	<%= link_to 'Show', @video %> .
	<%= link_to 'Back', videos_path %>
</div>

app/views/videos/index.html.erb
<% if user_signed_in? %>
	<%= link_to 'New Video', new_video_path , class: 'btn btn-default'%>
<% end %>

<% @videos.each do |video| %>
    <div class="post-block">
	    <div class="round-image-50"><%= image_tag video.user.avatar.url(:thumb) %></div>
	    <h4>
	        <%= link_to video.title, video_path(video)  %><br>
	      <small class="author">Submitted <%= time_ago_in_words(video.created_at) %> by <%= video.user.name %></small>
	    </h4>
	      <div><%= embed(video.url) %></div>
	      <div class="btn-group">
		      <%= link_to 'Show', video ,class: 'btn btn-default btn-sm' %>
		      <% if user_signed_in? and current_user.id == video.user_id %>
			      <%= link_to 'Edit', edit_video_path(video) ,class: 'btn btn-default btn-sm' %>
			      <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-default btn-sm' %>
		    <% end %>
		  </div>
		  <br/>
		    <%= video.description %>
    </div>
<% end %>
<br>

app/views/videos/new.html.erb
<div class="post-block">
	<div class="page-header"><h1>New Video</h1></div>
	<%= render 'form' %>
	<%= link_to 'Back', videos_path %>
</div>

app/views/videos/show.html.erb
<div class="post-block">
	<div class="page-header">
	  <h1><%= @video.title %>
	  <br><small>Submitted By <%= @video.user.name %></small></h1>
	</div>

	<p>
	  <strong>Description:</strong>
	  <%= @video.description %>
	</p>

	<div class="embed-container">
	  <%= embed(@video.url) %>
	</div>

	<% if current_user==@video.user %>
	 	<div class="btn-group">
			<%= link_to 'Edit',edit_video_path(@video), class: "btn btn-default" %>
	      <%= link_to 'Destroy', @video, method: :delete,data: {confirm: 'Are you sure?'},class: "btn btn-default"%>
	    </div>
	<% end %>

	<%= render "votes/show" %>
	<%= render "comments/index" %> 
	<%= render  "comments/new" %>
</div>