config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: "registrations"}
  root 'home#index'

  resources :comments do   
     resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
  end

  resources :articles do 
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do 
      resources :comments  
    end
  end

  resources :links do 
    resource :vote do
      put 'upvote'
      put 'downvote'
    end
    resources :comments do
      resources :comments  
    end
  end

  resources :videos do
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do
      resources :comments  
    end
  end

  resources :photos do
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do  
      resources :comments  
    end
  end

  

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :votes, :as => :votable, :dependent => :destroy
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @commentable=@link
    @comments = @commentable.comments
    @comment = Comment.new

    @votable=@link
    # @likes = @votable.votes.where(:emotion => 1).count
    # @dislikes = @votable.votes.where(:emotion => 2).count
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def upvote
  #   @link=Link.find(params[:id])
  #   @link.upvote_by current_user
  #   redirect_to :back
  # end

  # def downvote
  #   @link=Link.find(params[:id])
  #   @link.downvote_by current_user
  #   redirect_to :back
  # end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <%= render 'shared/errors', object: @link %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :url %><br>
    <%= f.text_field :url ,class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit "Submit Link", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/links/edit.html.erb
<div class="post-block">
	<div class="page-header"><h1>Editing Link</h1></div>

	<%= render 'form' %>

	<%= link_to 'Show', @link %> .
	<%= link_to 'Back', links_path %>
</div>

app/views/links/index.html.erb
<% if user_signed_in? %>
	<%= link_to 'Add link', new_link_path , class: 'btn btn-default'%>
<% end %>

<% @links.each do|link| %>
  <div class="post-block">
  	<div class="round-image-50"><%= image_tag link.user.avatar.url(:thumb) %></div>
     <h4>
        <%= link_to link.title, link  %><br>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.name %></small>
      </h4>
      <div class="btn-group">
        <a target="_blank" class="btn btn-default btn-sm" href="<%= link.url %>">Visit Link</a>
        <% if user_signed_in? and current_user.id == link.user_id %>
			<%= link_to 'Edit', edit_link_path(link) ,class: 'btn btn-default btn-sm' %>
			<%= link_to 'Delete', link, method: :delete, data: {confirm: 'Are you sure'} ,class: 'btn btn-default btn-sm' %>
		<% end %>
      </div>
  </div>
<% end %>

app/views/links/new.html.erb
<div class="post-block">
	<div class="page-header"><h1>New Link</h1></div>
	<%= render 'form' %>
	<%= link_to 'Back', links_path %>
</div>

app/views/links/show.html.erb
<div class="post-block">
	<div class="page-header">
	  <h1><a href="<%= @link.url %>"><%= @link.title %></a><br><small>Submitted By <%= @link.user.name %></small></h1>
	</div>

	<div class="btn-group">
	  <%= link_to 'Visit URL', @link.url, class:"btn btn-primary" , target: "_blank"%>
	</div>

	<% if current_user==@link.user %>
	    <div class="btn-group">
	      <%= link_to 'Edit',edit_link_path(@link), class: "btn btn-default" %>
	      <%= link_to 'Destroy', @link, method: :delete,data: {confirm: 'Are you sure?'},class: "btn btn-default"%>
	    </div>
	<% end %>
	
	<%= render "votes/show" %>
	<%= render  "comments/new" %>
	<%= render "comments/index" %> 
	
</div>