config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { registrations: "registrations"}
  root 'home#index'

  resources :comments do   
     resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
  end

  resources :articles do 
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do 
      resources :comments  
    end
  end

  resources :links do 
    resource :vote do
      put 'upvote'
      put 'downvote'
    end
    resources :comments do
      resources :comments  
    end
  end

  resources :videos do
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do
      resources :comments  
    end
  end

  resources :photos do
    resource :vote do #use singular resource for not generating the :id
      put 'upvote'
      put 'downvote'
    end
    resources :comments do  
      resources :comments  
    end
  end

  

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :as => :commentable
	has_many :votes, :as => :votable
	
	has_attached_file :image

	validates_attachment :image, content_type: {content_type: ["image/jpeg", "image/gif", "image/png"]}
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :set_photo, only: [:show, :edit, :delete, :destroy]
	before_action :authenticate_user!, except: [:index,:show]

	def index 
		@photos = Photo.order('created_at')
	end

	def new 
		@photo = current_user.photos.build
	end

	def create
		@photo = current_user.photos.build(photo_params)
		if @photo.save
			flash[:success] = 'The photo was added!'
			redirect_to :photos
		else
			render 'new'
		end
	end

	def destroy
		@photo.destroy
		respond_to do |format|
			format.html {redirect_to photos_url, notice: 'Photo successfully destroyed.'}
			format.json { head :no_content }
		end
	end

	def edit	
	end

	def show
		@photo = Photo.find(params[:id])
		@commentable=@photo
	    @comments = @commentable.comments
	    @comment = Comment.new

	    @votable=@photo
	    # @likes = @votable.votes.where(:emotion => 1).count
	    # @dislikes = @votable.votes.where(:emotion => 2).count
	end

	private

	def photo_params
		params.require(:photo).permit(:image, :title,:user_id,:photo_id)
	end

	def set_photo
		@photo = Photo.find(params[:id])
	end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for @photo do |f| %>
	<%= render 'shared/errors', object: @photo %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image%>
	</div>
	<div class="form-group">
		<%= f.submit 'Upload Photo', class: "btn btn-lg btn-primary" %>
	</div>
<% end %>

app/views/photos/edit.html.erb
<div class="post-block">
	<div class="page-header"><h1>Editing Photo</h1></div>
	<%= render 'form' %>

	<%= link_to 'Show', @photo %> .
	<%= link_to 'Back', photos_path %>
</div>

app/views/photos/index.html.erb
<% if user_signed_in? %>
	<%= link_to 'Upload Photo', new_photo_path, class: 'btn btn-default' %>
<% end %>

<% @photos.each do |photo| %>
<div class="post-block">
	<div class="media">
		<div class="round-image-50"><%= image_tag photo.user.avatar.url(:thumb) %></div>
		<h4>
        <%= link_to photo.title, photo_path(photo)  %><br>
        <small class="author">Submitted <%= time_ago_in_words(photo.created_at) %> by <%= photo.user.name %></small>
        </h4>
		<%= link_to image_tag(photo.image.url, class: 'media-object'), photo.image.url, target: '_blank' %>
	</div>
	<div class="btn-group">
		<%= link_to 'Show', photo, class: 'btn btn-default btn-sm' %>

		<% if user_signed_in? and current_user.id == photo.user_id %>
			<%= link_to 'Edit', edit_photo_path(photo) ,class: 'btn btn-default btn-sm' %>
			<%= link_to 'Delete', photo, method: :delete, data: {confirm: 'Are you sure'} ,class: 'btn btn-default btn-sm' %>
		<% end %>
	</div>
	
</div>
<% end %>

app/views/photos/new.html.erb
<div class="post-block">
	<div class="page-header"><h1>Upload Photo</h1></div>	
	<%= render 'form' %>
	<%= link_to "Back", photos_path %>
</div>

app/views/photos/show.html.erb
<div class="post-block">
	<div class="media">
		<div class="page-header">
			<h1><%= @photo.title %>
			<br><small>Submitted By <%= @photo.user.name %></small></h1>
		</div>
		<p>
			<%= link_to image_tag(@photo.image.url, class: 'media-object'), @photo.image.url, target: '_blank' %>
		</p>
	</div>
	
	<% if current_user==@photo.user %>
	 	<div class="btn-group">
			<%= link_to 'Edit',edit_photo_path(@photo), class: "btn btn-default" %>
	      <%= link_to 'Destroy', @photo, method: :delete,data: {confirm: 'Are you sure?'},class: "btn btn-default"%>
	    </div>
	<% end %>

	<%= render "votes/show" %>
	<%= render  "comments/new" %>
	<%= render "comments/index" %> 

</div>